namespace Ecommerce.Application.DTOs.Addresses;

public record AddressDto(
    Guid Id,
    int Type,
    string Label,
    string? ContactName,
    string Street,
    string? ExternalNumber,
    string? InternalNumber,
    string? Neighborhood,
    string? Municipality,
    string City,
    string State,
    string PostalCode,
    string Country,
    string Phone,
    string? References,
    string? DeliveryInstructions,
    decimal? Latitude,
    decimal? Longitude,
    bool IsDefault);

public record SaveAddressRequest(
    Guid? Id,
    int Type,
    string Label,
    string ContactName,
    string Street,
    string ExternalNumber,
    string? InternalNumber,
    string Neighborhood,
    string Municipality,
    string? City,
    string State,
    string PostalCode,
    string Country,
    string Phone,
    string? References,
    string? DeliveryInstructions,
    decimal? Latitude,
    decimal? Longitude,
    bool IsDefault);
